:doctype: book
:toc: left
:toclevels: 2
:source-highlighter: pygments
:source-language: C++
:prewrap!:
:pygments-style: vs
:icons: font

= Circular Array

[NOTE]
.Precondition
====
[source,c++]
----
namespace circular = trial::circular;
----
====

== Introduction

The `circular::array<T, N>` template class is a fixed-size double-ended circular queue.

The circular array has a _fixed size_, which means there can be at most `N` elements
in the circular array, where `N` is determined at compile-time. Like `std::array<T, N>`,
all `N` elements within the storage of the circular array are default constructed
when the circular array is instantiated.
Although all elements in the embedded array are constructed, the circular array
will appear as empty. Inserting elements will overwrite the default constructed
elements.

== Tutorial

=== Running Average

In the <<span.adoc#span-tutorial,circular span tutorial>> we ended up with a class
definition for a running average containing both an array and a span.
[source,c++,numbered]
----
template <typename T, std::size_t N>
class waverage
{
public:
    using value_type = T; 

    // Member functions...

private:
    static_assert(N > 0, "N must be greater than zero");
    value_type current_mean = {};
    // Storage and window
    value_type storage[N];
    circular::span<value_type, N> window;
};
----
Combining a fixed-size storage with a circular span is exactly the purpose of
the circular array, so we can replace the storage and span with
`circular::array<T, N>`.
[source,c++,numbered]
----
template <typename T, std::size_t N>
class waverage
{
public:
    using value_type = T; 

    // Member functions...

private:
    static_assert(N > 0, "N must be greater than zero");
    value_type current_mean = {};
    // Window contains storage
    circular::array<value_type, N> window;
};
----

== Design Rationale

This section describes the choices behind the design of the circular array.

The <<span.adoc#span-rationale,design rationale>> of `circular::span<T, N>` also applies,
except the ability to use `dynamic_extent`.

=== std::array

The circular array, being a fixed-size container, is modeled after `std::array<T, N>`.
The storage is located inside the circular array, which gives good locality and this
cache performance, but move is linear time complexity.

There are some significant deviations.

 - The circular array keeps track of the number of inserted elements. Although
   the underlying storage is filled with default constructed elements, they do
   not count as inserted elements. Inserted elements are those that have been
   assigned to the container, or that have been pushed to the front or the back.
 - The circular array does not have <<span.adoc#rationale-no-mutable-iterator,mutable iterators>>
   and therefore does not model the _Container_ concept.
 - The circular array does not fulfill the _ContiguousContainer_ requirements
   even though the storage is contiguous. This is because the circular array
   can wrap around the end of the storage, so it cannot fulfill the
   _ContiguousIterator_ concept.

== Reference

Defined in header `<trial/circular/array.hpp>`.

Defined in namespace `trial::circular`.
[source,c++]
----
template <
    typename T,
    std::size_t N
> class array;
----

The circular array is a fixed-size circular queue.

The _size_ is the current number of elements in the circular array.

The _capacity_ is the maximum number of elements that can be inserted without
overwriting old elements.
The capacity is set to `N` at compile-time and cannot be changed at run-time.

The underlying storage will default construct `N` elements at construction-time.
Inserting elements into the circular array will overwrite elements in the
storage. Erasing elements from the circular array will leave the elements
in the storage either untouched or in a moved-from state. The only guarantee
given with regards to the elements in the storage is that they are in a
valid state and therefore can either can be overwritten when new elements
are inserted or destroyed when the circular array is destroyed.

=== Template arguments

[frame="topbot",grid="rows",stripes=none]
|===
| `T` | Element type.
 +
 +
 _Constraint:_ `T` must be a complete type.
 +
 _Constraint:_ `T` must be _DefaultConstructible_.
 +
 _Constraint:_ `T` must be _Erasable_.
| `N` | The maximum number of elements in the span.
 +
 +
 _Constraint:_ `N` cannot be `dynamic_extent`.
|===

=== Member types

[%header,frame="topbot",grid="rows",stripes=none]
|===
| Member type | Definition
| `element_type` | `T`
| `value_type` | `std::remove_cv_t<T>`
| `size_type` | `std::size_t`
| `reference` | `element_type&`
| `const_reference` | `const element_type&`
| `const_iterator` | _BidirectionalIterator_ with `const value_type`
| `const_reverse_iterator` | `std::reverse_iterator<const_iterator>`
| `const_segment` | _BidirectionalRange_ with `const value_type`
|===
Notice that there are <<rationale-no-mutable-iterator,no mutable iterators>>.

=== Member functions

[%header,frame="topbot",grid="rows",stripes=none]
|===
| Member function | Description
| `constexpr array() noexcept` | Creates an empty circular array.
 +
 +
 The `N` elements of the underlying storage are default constructed.
 +
 +
 _Ensures:_ `capacity() == N`
 +
 _Ensures:_ `size() == 0`
| `constexpr array(const array<T, N>& other) noexcept(_see Remarks_)` | Creates a circular array by copying.
 +
 +
 _Constraint:_ `T` must be _CopyConstructible_.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _CopyConstructible_.
| `constexpr array(array<T, N>&& other) noexcept(_see Remarks_)` | Creates a circular array by moving.
 +
 +
 _Constraint:_ `T` must be _MoveConstructible_.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveConstructible_.
| `template <typename... Args>
 +
 constexpr array(value_type, Args&&...) noexcept(_see Remarks_)` | Creates a circular array with elements from input.
 +
 +
 This constructor emulates aggregate initialization.
 +
 +
 _Ensures:_ `capacity() == N`
 +
 _Ensures:_ `size() == std::min(input.size(), N)`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveAssignable_. 
| `constexpr{wj}footnote:constexpr11[Not constexpr in pass:[C++11].] array& operator=(const array<T, N>& other) noexcept(_see Remarks_)` | Recreates circular array by copying.
 +
 +
 _Constraint:_ `T` must be _CopyAssignable_.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _CopyAssignable_.
| `constexpr{wj}footnote:constexpr11[] array& operator=(array&& other) noexcept(_see Remarks_)` | Recreates circular array by moving.
 +
 +
 All elements are inserted, but if `input.size() > N` then only the last `N` input
 elements will remain in the circular array.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveAssignable_.
| `constexpr{wj}footnote:constexpr11[] array& operator=(std::initializer_list<value_type> input) noexcept(_see Remarks_)` | Recreates circular array with elements from initializer list.
 +
 +
 All elements are inserted, but if `input.size() > N` then only the last `N` input
 elements will remain in the circular array.
 +
 +
 _Ensures:_ `capacity() == N`
 +
 _Ensures:_ `size() == std::min(input.size(), N)`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveAssignable_. 
| `constexpr bool empty() const noexcept` | Checks if circular array is empty.
 +
 +
 Empty means that `size() == 0`.
| `constexpr bool full() const noexcept` | Checks if circular array is full.
 +
 +
 Full means that `size() == capacity()`.
| `constexpr size_type capacity() const noexcept` | Returns the maximum possible number of elements in the circular array.
| `constexpr size_type size() const noexcept` | Returns the number of elements in the circular array.
| `constexpr size_type max_size() const noexcept` | Returns the maximum possible number of elements in the circular array.
| `constexpr{wj}footnote:constexpr11[] reference front() noexcept` | Returns a reference to the first element in the circular array.
 +
 +
 _Expects:_ `size() > 0`
| `constexpr const_reference front() const noexcept` | Returns a constant reference to the first element in the circular array.
 +
 +
 _Expects:_ `size() > 0`
| `constexpr{wj}footnote:constexpr11[] reference back() noexcept` | Returns a reference to the last element in the circular array.
 +
 +
 _Expects:_ `size() > 0`
| `constexpr const_reference back() const noexcept` | Returns a constant reference to the last element in the circular array.
 +
 +
 _Expects:_ `size() > 0`
| `constexpr const_segment front_segment() const noexcept` | Returns a range of the first contiguous segment of the circular array.
 +
 +
 The front segment covers all elements from the beginning of the circular array until the end of the
 underlying storage if the circular array crosses the end of the storage; otherwise until the end of
 the circular array.
 +
 +
 An empty segment is returned if the circular array is empty.
 +
 +
 _Expects:_ `capacity() > 0`
| `constexpr const_segment back_segment() const noexcept` | Returns a range of the last contiguous segment of the circular array.
 +
 +
 The back segment covers the remaining elements not covered by the front segment.
 +
 +
 An empty segment is returned if the circular array is empty or does not cross the end of the
 underlying storage. Otherwise, the back segment starts at the beginning of the underlying
 storage and ends at the end of the circular array.
 +
 +
 _Expects:_ `capacity() > 0`
| `constexpr{wj}footnote:constexpr11[] reference operator[](size_type position) noexcept` | Returns a reference to the element at the given position in the circular array.
 +
 +
 _Expects:_ `position < size()`
| `constexpr const_reference operator[](size_type positon) const noexcept` | Returns a reference to the element at the given position in the circular array.
 +
 +
 _Expects:_ `position < size()`
| `constexpr{wj}footnote:constexpr11[] void clear() noexcept` | Clears the circular array.
 +
 +
 The elements in the underlying storage are not destroyed.
 +
 +
 _Ensures:_ `capacity() == N`
 +
 _Ensures:_ `size() == 0`
| `template <typename InputIterator>
 +
 constexpr{wj}footnote:constexpr11[] void assign(InputIterator first, InputIterator last) noexcept(_see Remarks_)` | Replaces the circular array with elements from iterator range.
 +
 +
 _Ensures:_ `size() == std::min(std::distance(first, last), capacity())`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _CopyAssignable_.
| `constexpr{wj}footnote:constexpr11[] void assign(std::initializer_list<value_type> input) noexcept(_see Remarks_)` | Replaces the circular array with elements from initializer list.
 +
 +
 _Ensures:_ `size() == std::min(input.size(), capacity())`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveAssignable_.
| `constexpr{wj}footnote:constexpr11[] void push_front(value_type) noexcept(_see Remarks_)` | Inserts an element at the beginning of the circular array.
 +
 +
 If the circular array is full, then the element at the end of the circular array is silently erased to make room for the new element.
 +
 +
 _Expects:_ `capacity() > 0`
 +
 +
 _Ensures:_ `size() \<= capacity()`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveAssignable_.
| `template <typename InputIterator>
 +
 constexpr{wj}footnote:constexpr11[] void push_front(InputIterator first, InputIterator last) noexcept(_see Remarks_)` | Inserts elements from iterator range at the beginning of the circular array.
 +
 +
 _Constraint:_ `value_type` must be _CopyAssignable_.
 +
 +
 _Expects:_ `capacity() > 0`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _CopyAssignable_.
| `constexpr{wj}footnote:constexpr11[] void push_back(value_type) noexcept(_see Remarks_)` | Inserts an element at the end of the circular array.
 +
 +
 If the circular array is full, then the element at the beginning of the circular array is silently erased to make room for the new element.
 +
 +
 _Expects:_ `capacity() > 0`
 +
 +
 _Ensures:_ `size() \<= capacity()`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveAssignable_.
| `template <typename InputIterator>
 +
 constexpr{wj}footnote:constexpr11[] void push_back(InputIterator first, InputIterator last) noexcept(_see Remarks_)` | Inserts elements from iterator range at the end of the circular array.
 +
 +
 _Constraint:_ `value_type` must be _CopyAssignable_.
 +
 +
 _Expects:_ `capacity() > 0`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _CopyAssignable_.
| `constexpr{wj}footnote:constexpr11[] value_type pop_front() noexcept(_see Remarks_)` | Removes and returns an element from the beginning of the circular array.
 +
 +
 The removed element in the underlying storage is left in a moved-from state.
 +
 +
 If the return value is unused, then `remove_front()` is a more efficient method for removing the front element.
 +
 +
 _Expects:_ `size() > 0`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveConstructible_.
| `constexpr{wj}footnote:constexpr11[] value_type pop_back() noexcept(_see Remarks_)` | Removes and returns an element from the end of the circular array.
 +
 +
 The removed element in the underlying storage is left in a moved-from state.
 +
 +
 If the return value is unused, then `remove_back()` is a more efficient method for removing the back element.
 +
 +
 _Expects:_ `size() > 0`
 +
 +
 _Remarks:_ `noexcept` if `value_type` is nothrow _MoveConstructible_.
| `constexpr{wj}footnote:constexpr11[] void append_front() noexcept`
 +
 +
 `constexpr{wj}footnote:constexpr11[] void append_front(size_type count) noexcept`
 | Inserts the given number of unspecified elements at the beginning of the circular array.
 +
 +
 The default value of `count` is 1 if omitted.
 +
 +
 Makes room for `count` elements at the front. The inserted elements are in an unspecified but valid state.
 +
 +
 If the circular array is full, then the elements are taken from the end of the circular array. This effectively rotates the circular array without touching the elements in the underlying storage. Otherwise, the circular array is enlarged.
 +
 +
 _Expects:_ `capacity() > 0`
 +
 _Expects:_ `count \<= capacity()`
 +
 +
 _Ensures:_ `size() >= count`
|  `constexpr{wj}footnote:constexpr11[] void append_back() noexcept`
 +
 +
 `constexpr{wj}footnote:constexpr11[] void append_back(size_type count) noexcept`
 | Inserts the given number of unspecified elements at the end of the circular array.
 +
 +
 The default value of `count` is 1 if omitted.
 +
 +
 Makes room for `count` elements at the back. The inserted elements are in an unspecified but valid state.
 +
 +
 If the circular array is full, then the elements are taken from the beginning of the circular array. This effectively rotates the circular array without touching the elements in the underlying storage. Otherwise, the circular array is enlarged.
 +
 +
 _Expects:_ `capacity() > 0`
 +
 _Expects:_ `count \<= capacity()`
 +
 +
 _Ensures:_ `size() >= count`
|  `constexpr{wj}footnote:constexpr11[] void remove_front() noexcept`
 +
 +
 `constexpr{wj}footnote:constexpr11[] void remove_front(size_type count) noexcept`
 | Removes the given number of elements from the beginning of the circular array.
 +
 +
 The default value of `count` is 1 if omitted.
 +
 +
 The removed elements are not destroyed in the underlying storage.
 +
 +
 _Expects:_ `size() > 0`
 +
 _Expects:_ `count \<= size()`
 +
 +
 _Ensures:_ `capacity() - size() >= count`
| `constexpr{wj}footnote:constexpr11[] void remove_back() noexcept`
 +
 +
 `constexpr{wj}footnote:constexpr11[] void remove_back(size_type count) noexcept`
 | Removes the given number of elements from the end of the circular array.
 +
 +
 The default value of `count` is 1 if omitted.
 +
 +
 The removed elements are not destroyed in the underlying storage.
 +
 +
 _Expects:_ `size() > 0`
 +
 _Expects:_ `count \<= size()`
 +
 +
 _Ensures:_ `capacity() - size() >= count`
| `constexpr const_iterator begin() const noexcept` | Returns an interator to the beginning of the circular array.
| `constexpr const_iterator end() const noexcept` | Returns an interator to the end of the circular array.
| `constexpr const_iterator cbegin() const noexcept` | Returns an interator to the beginning of the circular array.
| `constexpr const_iterator cend() const noexcept` | Returns an interator to the end of the circular array.
| `constexpr const_iterator rbegin() const noexcept` | Returns a reverse interator to the beginning of the circular array.
| `constexpr const_iterator rend() const noexcept` | Returns a reverse interator to the end of the circular array.
| `constexpr const_iterator crbegin() const noexcept` | Returns a reverse interator to the beginning of the circular array.
| `constexpr const_iterator crend() const noexcept` | Returns a reverse interator to the end of the circular array.
|===
