:doctype: book
:toc: left
:toclevels: 2
:source-highlighter: pygments
:source-language: C++
:prewrap!:
:pygments-style: vs
:icons: font

= Circular Span

== Introduction

The `circular::span<T>` template class is a span that turns continguous memory
into a double-ended circular queue.

[cols="20,80",frame="none",grid="none",stripes=none]
|===
| Span | The storage is not owned by the span. The owner of the memory is
   responsible for destroying the span before releasing the memory.
| Circular | Inserting elements into the span will remove elements at the
   other end of the span when the span is full. If elements always are inserted
   at the same end, then we effectively have a moving window over the most
   recent elements.
| Double-ended | Elements can be inserted either at the beginning or the end
   of the span. This enables fixed-sized first-in-first-out or last-in-first-out
   usages.
| Queue | Elements can only be inserted and erased at the beginning or end of
   the span.
|===

[#span-tutorial]
== Tutorial

Suppose we receive a sequence of numerical values one by one over time, and we
want to calculate the running average of the `N` most recent values. Our class
should at least support the following interface for inserting new values and
for returning the current mean.
[source,c++,numbered]
----
template <typename T, std::size_t N>
class waverage
{
public:
    using value_type = T; 

    waverage() noexcept;

    // Insert new value
    void push(value_type value) noexcept;
    // Return current mean
    value_type mean() const noexcept;
};
----
When we insert a new value, the oldest value must be removed from our running
average, so we have to remember the `N` most recent values.
We therefore want to reserve storage for `N` values, and have an efficient way
of inserting new values and removing old values from this storage.
We are going to use a circular span (`circular::span<value_type, N> window`)
that uses an array (`value_type storage[N]`) as storage.
[source,c++,numbered]
----
template <typename T, std::size_t N>
class waverage
{
public:
    using value_type = T; 

    waverage() noexcept;

    void push(value_type input) noexcept;
    value_type mean() const noexcept;

private:
    static_assert(N > 0, "N must be greater than zero");
    value_type sum = {};
    value_type storage[N];
    circular::span<value_type, N> window;
};
----
We start by initializing the circular span to use the array as storage.
[source,c++,numbered]
----
template <typename T, std::size_t N>
waverage::waverage()
    : window(storage) // Instruct span to use storage
{
}
----
Notice that the array is automatically filled with default-constructed elements.
These will be overwritten one by one when inserting new values into the window.

When new values are inserted we first update the running sum. This is done by
undoing the effect of the oldest value (`window.front()`) if the window is
full. There is a pre-condition for `span<T, N>::front()` that it can only be
called if the window is not empty; this is guaranteed by the call to `window.full()`.

Afterwards we store the input value in the window (`window.push_back(input)`)
such that we can undo its effect when it later leaves the window. As the
`push_back()` function overwrites the oldest value at the front, it is important
that we update the running sum before we store the input value.
[source,c++,numbered]
----
template <typename T, std::size_t N>
void waverage::push(value_type input) noexcept
{
    // Update the current mean
    if (window.full())
    {
        sum += input - window.front();
    }
    else
    {
        sum += input;
    }
    // Remember the input value for later use
    window.push_back(input);
}
----
The current mean is the calculated as the running sum divided by the number of
elements in the window.
[source,c++,numbered]
----
template <typename T, std::size_t N>
T waverage::mean() const noexcept
{
    assert(!window.empty());

    return sum / window.size();
}
----

== Design Rationale

This section describes the choices behind the design of the circular span.

[#rationale-extent]
=== Extent

The extent is an optional template argument that specifies the capacity of the
span at compile-time. The capacity is part of the span type and therefore does
not have to be stored as a member variable.

If the `Extent` template argument is omitted, or specified as `dynamic_extent`,
the capacity is determined when the span is constructed. The capacity does not
change after construction, unless the span is recreated by assignment. For this
case, the capacity is stored as a member variable.

The extent has been introduced for alignment with `std::span<T, Extent>`.

[#rationale-no-mutable-iterator]
=== No Mutable Iterators

Although `circular::span<T>` has been designed to work well with standard algorithms,
it has no mutable iterators. Some mutating algorithms may modify the storage of the
destination container in a way that causes the destination span to become invalid.

For instance `std::copy` copies the elements from one container into another
container by accessing the elements directly in storage, which means that the
container is not informed about those changes. Consequently, the internal state
of the input span is not copied to the destination span.

Therefore there is a `circular::span<T>::const_iterator` but no `circular::span<T>::iterator`.

Using `std::copy` with `std::front_inserter` or `std::back_inserter` does work as
expected though.

Mutable `operator[]` also exists.

[#rationale-no-subspans]
=== No subspans

There are no member functions in `circular::span<T>` to create a subspan.

There are no subspans that returns a circular span. Circular span iterators
are not contiguous because they may wrap around from the end of the storage
to the beginning. Circular span iterators can therefore not be used to
create a smaller circular span within an existing circular span.

There are no subspans that returns another type of span in order to avoid
introducing another span type, whether `std::span` or something like
`std::pair<pointer, size_type>`. Although it may be useful to identify the
two storage areas that constitute a wrapped-around circular span, these
can be easily calculated by the storage owner. For instance, an implementation
of `boost::circular_buffer` based on the circular span can use pointer
arithmetic.
[source,c++,numbered]
----
template <typename T, typename Allocator = std::allocator<T>>
class circular_buffer
    : private std::vector<T, Allocator>,
      private circular::span<T>
{
    using storage = std::vector<T, Allocator>;
    using span = circular::span<T>;

public:
    using size_type = typename span::size_type;
    using pointer = typename span::pointer;
    using array_range = std::pair<pointer, size_type>;

    array_range array_one()
    {
        const auto back_index = &span::back() - storage::data();
        return std::make_pair(&storage::front(), back_index + 1);
    }

    array_range array_two()
    {
        const auto front_index = &span::front() - storage::data();
        return std::make_pair(&storage::operator[](front_index),
                              (front_index != 0) * (span::capacity() - front_index));
    }
};
----

== Reference

Defined in header `<trial/circular/span.hpp>`.

Defined in namespace `trial::circular`.
[source,c++]
----
template <
    typename T,
    std::size_t Extent = dynamic_extent
> class span;
----
The span template class is a circular view of some external contiguous memory.

The extent determines the capacity of the span, that is the maximum number of
elements that the span can contain.
If `dynamic_extent` is used then the capacity is derived from the input arguments
at construction or assignment time. Otherwise the capacity is fixed to the
specified `Extent` template argument. Dynamic extent is used by default.

=== Template arguments

[frame="topbot",grid="rows",stripes=none]
|===
| `T` | Element type.
 +
 +
 _Constraint:_ `T` must be a complete type.
| `Extent` | The maximum number of elements in the span.
|===

=== Member types

[%header,frame="topbot",grid="rows",stripes=none]
|===
| Member type | Definition
| `element_type` | `T`
| `value_type` | `std::remove_cv_t<T>`
| `size_type` | `std::size_t`
| `pointer` | `element_type*`
| `reference` | `element_type&`
| `const_reference` | `const element_type&`
| `const_iterator` | _BidirectionalIterator_ with `const value_type`
| `const_reverse_iterator` | `std::reverse_iterator<const_iterator>`
|===
Notice that there are <<rationale-no-mutable-iterator,no mutable iterators>>.

=== Member functions

[%header,frame="topbot",grid="rows",stripes=none]
|===
| Member function | Description
| `constexpr span() noexcept` | Creates an empty span with zero capacity.
 +
 +
 No elements can be inserted into a zero-capacity span. The span must be recreated before use.
 +
 +
 _Ensures:_ `capacity() == 0`
 +
 _Ensures:_ `size() == 0`
| `constexpr span(const span& other) noexcept` | Creates a span by copying.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
| `constexpr span(span&& other) noexcept` | Creates span by moving.
 +
 +
 The state of the moved-from span is valid but undefined.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
| `template <typename U, std::size_t N>`
 +
`explicit constexpr span(const span<U, N>& other) noexcept` | Creates a span by copying from convertible value type or compatible extent.
 +
 +
 _Constraint:_ `Extent == N` or `Extent == dynamic_extent`
 +
 _Constraint:_ `U` is convertible to `T`
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
| `template <typename ContiguousIterator>`
 +
`constexpr span(ContiguousIterator begin, ContiguousIterator end) noexcept` | Creates a span from iterators.
 +
 +
 _Ensures:_ `capacity() == std::distance(begin, end)`
 +
 _Ensures:_ `size() == std::distance(begin, end)`
| `template <typename ContiguousIterator>`
 +
`constexpr span(ContiguousIterator begin, ContiguousIterator end, ContiguousIterator first, size_type length) noexcept` | Creates a span from iterators and initializes the span with the pre-existing `length` elements starting at `first`.
 +
 +
 _Expects:_ `first` is within the range `[begin; end]`
 +
 _Expects:_ `length \<= std::distance(first, end)`
 +
 +
 _Ensures:_ `capacity() == std::distance(begin, end)`
 +
 _Ensures:_ `size() == length`
| `template <std::size_t N>`
 +
`explicit constexpr span(value_type (&)[N]) noexcept` | Creates empty span from array with compatible extent.
 +
 +
 _Constraint:_ `Extent == N` or `Extent == dynamic_extent`
 +
 +
 _Ensures:_ `capacity() == N`
 +
 _Ensures:_ `size() == 0`
| `constexpr`{wj}footnote:constexpr11[Not constexpr in pass:[C++11].] `span& operator=(const span& other) noexcept` | Recreates span by copying.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
| `constexpr`{wj}footnote:constexpr11[] `span& operator=(span&&) noexcept` | Recreates span by moving.
 +
 +
 The state of the moved-from span is valid but undefined.
 +
 +
 _Ensures:_ `capacity() == other.capacity()`
 +
 _Ensures:_ `size() == other.size()`
| `constexpr`{wj}footnote:constexpr11[] `span& operator=(std::initializer_list<value_type>) noexcept(/* condition */)` | Replaces span with elements from initializer list.
 +
 +
 _Constraint:_ `value_type` must be _MoveAssignable_.
 +
 +
noexcept if `value_type` is nothrow _MoveAssignable_.
| `constexpr bool empty() const noexcept` | Checks if span is empty.
| `constexpr bool full() const noexcept` | Checks if span is full.
| `constexpr size_type capacity() const noexcept` | Returns the maximum possible number of elements in the span.
| `constexpr size_type size() const noexcept` | Returns the number of elements in the span.
| `constexpr`{wj}footnote:constexpr11[] `reference front() noexcept` | Returns a reference to the first element in the span.
 +
 +
 _Expects:_ `!empty()`
| `constexpr const_reference front() const noexcept` | Returns a constant reference to the first element in the span.
 +
 +
 _Expects:_ `!empty()`
| `constexpr`{wj}footnote:constexpr11[] `reference back() noexcept` | Returns a reference to the last element in the span.
 +
 +
 _Expects:_ `!empty()`
| `constexpr const_reference back() const noexcept` | Returns a constant reference to the last element in the span.
 +
 +
 _Expects:_ `!empty()`
| `constexpr`{wj}footnote:constexpr11[] `reference operator[](size_type pos) noexcept` | Returns a reference to the element at the specified position in the span.
 +
 +
 _Expects:_ `pos < size()`
| `constexpr const_reference operator[](size_type pos) const noexcept` | Returns a reference to the element at the specified position in the span.
 +
 +
 _Expects:_ `pos < size()`
| `constexpr`{wj}footnote:constexpr11[] `void clear() noexcept` | Clears the span. The elements in the underlying storage are not destroyed.
 +
 +
 _Ensures:_ `size() == 0`
| `template <typename InputIterator>`
 +
 `constexpr`{wj}footnote:constexpr11[] `void assign(InputIterator first, InputIterator last) noexcept(/* condition */)` | Replaces the span with elements from iterator range.
  +
  +
noexcept if `value_type` is nothrow _CopyAssignable_.
| `constexpr`{wj}footnote:constexpr11[] `void assign(std::initializer_list<value_type>) noexcept(/* condition */)` | Replaces the span with elements from initializer list.
 +
 +
noexcept if `value_type` is nothrow _MoveAssignable_.
| `constexpr`{wj}footnote:constexpr11[] `void push_front(value_type) noexcept(/* condition */)` | Inserts an element at the beginning of the span. If the span is full, then the element at the end of the span is silently erased to make room for new element.
 +
 +
noexcept if `value_type` is nothrow _MoveAssignable_.
| `constexpr`{wj}footnote:constexpr11[] `void push_back(value_type) noexcept(/* condition */)` | Inserts an element at the end of the span. If the span is full, then the element at the beginning of the span is silently erased to make room for new element.
 +
 +
noexcept if `value_type` is nothrow _MoveAssignable_.
| `constexpr`{wj}footnote:constexpr11[] `void pop_front(size_type) noexcept` | Erases the specified number of elements from the beginning of the span. If the argument is omitted, then only one element is erased.
| `constexpr`{wj}footnote:constexpr11[] `void pop_back(size_type) noexcept` | Erases the specified number of elements from the end of the span. If the argument is omitted, then only one element is erased.
| `constexpr`{wj}footnote:constexpr11[] `value_type move_front() noexcept(/* condition */)` | Erases and returns an element from the beginning of the span.
 +
 +
noexcept if `value_type` is nothrow _MoveConstructible_.
| `constexpr`{wj}footnote:constexpr11[] `value_type move_back() noexcept(/* condition */)` | Erases and returns an element from the end of the span.
 +
 +
noexcept if `value_type` is nothrow _MoveConstructible_.
| `constexpr`{wj}footnote:constexpr11[] `void advance_left(size_type) noexcept(/* condition */)` | Rotates the span left by the specified amount.
 +
 +
If the span is full, then the internal state is updated to emulate a rotate, but leaving the elements in their original memory position. Constant time complexity.
 +
 +
If the span is not full, then elements are moved. Linear time complexity.
 +
 +
noexcept if `value_type` is nothrow _MoveConstructible_ and _MoveAssignable_.
| `constexpr`{wj}footnote:constexpr11[] `void advance_right(size_type) noexcept(/* condition */)` | Rotates the span right by the specified amount.
 +
 +
If the span is full, then the internal state is updated to emulate a rotate, but leaving the elements in their original memory position. Constant time complexity.
 +
 +
If the span is not full, then elements are moved. Linear time complexity.
 +
 +
noexcept if `value_type` is nothrow _MoveConstructible_ and _MoveAssignable_.
| `constexpr`{wj}footnote:constexpr11[] `void normalize() noexcept(/* condition */)` | Rotates elements such that the span starts at the beginning of the storage. Normalization invalidates pointers and references, but does not invalidate iterators.
 +
 +
noexcept if `value_type` is nothrow _Swappable_.
| `constexpr bool is_normalized() const noexcept` | Checks if the span is normalized.
| `constexpr const_iterator begin() const noexcept` | Returns an interator to the beginning of the span.
| `constexpr const_iterator end() const noexcept` | Returns an interator to the end of the span.
| `constexpr const_iterator cbegin() const noexcept` | Returns an interator to the beginning of the span.
| `constexpr const_iterator cend() const noexcept` | Returns an interator to the end of the span.
| `constexpr const_iterator rbegin() const noexcept` | Returns a reverse interator to the beginning of the span.
| `constexpr const_iterator rend() const noexcept` | Returns a reverse interator to the end of the span.
| `constexpr const_iterator crbegin() const noexcept` | Returns a reverse interator to the beginning of the span.
| `constexpr const_iterator crend() const noexcept` | Returns a reverse interator to the end of the span.
|===

=== Non-member constants
[frame="topbot",grid="rows"]
|===
| `dynamic_extent` | A constant of type `std::size_t` to specify a span with dynamic extent.
|===
